namespace Clay;

/// <summary>Stable key values matching Clay's public C ABI.</summary>
public enum ClayKey
{
    None = 0,
    Escape,
    Enter,
    Tab,
    Space,
    Backspace,
    Delete,
    Home,
    End,
    PageUp,
    PageDown,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    A, B, C, D, E, F, G, H, I, J, K, L, M,
    N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    Digit0, Digit1, Digit2, Digit3, Digit4,
    Digit5, Digit6, Digit7, Digit8, Digit9,
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
    Quote,
    Comma,
    Period,
    Slash,
    Semicolon,
    Minus,
    Equals,
    BracketLeft,
    BracketRight,
    Backslash,
    Grave,
    MouseLeft,
    MouseRight,
    MouseMiddle,
    MouseX1,
    MouseX2,
    WheelUp,
    WheelDown,
    GamepadA,
    GamepadB,
    GamepadX,
    GamepadY,
    GamepadLeftBumper,
    GamepadRightBumper,
    GamepadBack,
    GamepadStart,
    GamepadLeftStick,
    GamepadRightStick,
    GamepadDpadUp,
    GamepadDpadDown,
    GamepadDpadLeft,
    GamepadDpadRight,
    LeftShift,
    LeftControl,
    LeftAlt,
    LeftMeta,
}
