<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Clay.Godot</AssemblyName>
    <RootNamespace>Clay</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ClayRuntime.cs" />
  </ItemGroup>
</Project>
