<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>Clay.Godot</AssemblyName>
    <RootNamespace>Clay</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../ClayRuntime.cs" Link="ClayRuntime.cs" />
    <Compile Include="../ClayKey.cs" Link="ClayKey.cs" />
    <Compile Include="../ClayModifiers.cs" Link="ClayModifiers.cs" />
  </ItemGroup>
</Project>
